const ClientTypes = {
  SET_CLIENT_DATA:           'SET_CLIENT_DATA',
  SET_CLIENT_CURRENT_PAGE:   'SET_CLIENT_CURRENT_PAGE',
  SET_CLIENT_SORT:           'SET_CLIENT_SORT',
  SET_CLIENT_ORDER:          'SET_CLIENT_ORDER',
  SET_CLIENT_TOTAL_PAGE:     'SET_CLIENT_TOTAL_PAGE',
  SET_CLIENT_ID:             'SET_CLIENT_ID',
  SET_CLIENT_ACTION:         'SET_CLIENT_ACTION',
  SET_CLIENT_RECORD:         'SET_CLIENT_RECORD'
}

export default ClientTypes;