const SubscriptionTypes = {
  SET_SUBSCRIPTION_DATA:           'SET_SUBSCRIPTION_DATA',
  SET_SUBSCRIPTION_CURRENT_PAGE:   'SET_SUBSCRIPTION_CURRENT_PAGE',
  SET_SUBSCRIPTION_SORT:           'SET_SUBSCRIPTION_SORT',
  SET_SUBSCRIPTION_ORDER:          'SET_SUBSCRIPTION_ORDER',
  SET_SUBSCRIPTION_TOTAL_PAGE:     'SET_SUBSCRIPTION_TOTAL_PAGE',
  SET_SUBSCRIPTION_ID:             'SET_SUBSCRIPTION_ID',
  SET_SUBSCRIPTION_ACTION:         'SET_SUBSCRIPTION_ACTION',
  SET_SUBSCRIPTION_USER_ID_ACTION: 'SET_SUBSCRIPTION_USER_ID_ACTION',
  SET_SUBSCRIPTION_RECORD:         'SET_SUBSCRIPTION_RECORD',
  SET_SUBSCRIPTION_ACTIVATED:      'SET_SUBSCRIPTION_ACTIVATED',
  RESET_SUBSCRIPTION:              'RESET_SUBSCRIPTION'
}

export default SubscriptionTypes;