const TariffTypes = {
  SET_TARIFF_DATA:           'SET_TARIFF_DATA',
  SET_TARIFF_CURRENT_PAGE:   'SET_TARIFF_CURRENT_PAGE',
  SET_TARIFF_SORT:           'SET_TARIFF_SORT',
  SET_TARIFF_ORDER:          'SET_TARIFF_ORDER',
  SET_TARIFF_TOTAL_PAGE:     'SET_TARIFF_TOTAL_PAGE',
  SET_TARIFF_ID:             'SET_TARIFF_ID',
  SET_TARIFF_ACTION:         'SET_TARIFF_ACTION',
  SET_TARIFF_SERVICE_ID:     'SET_TARIFF_SERVICE_ID',
  SET_TARIFF_RECORD:         'SET_TARIFF_RECORD'
}

export default TariffTypes;