const BreadcrumbsTypes = {
  SET_BREADCRUMB_DATA: 'SET_BREADCRUMB_DATA',
  SET_BREADCRUMB_ACTIVE: 'SET_BREADCRUMB_ACTIVE',
  SET_COMBINE_REDUX: 'SET_COMBINE_REDUX',
};

export default BreadcrumbsTypes;
