const DocumentTypes = {
  SET_DOCUMENT_DATA:           'SET_DOCUMENT_DATA',
  SET_DOCUMENT_CURRENT_PAGE:   'SET_DOCUMENT_CURRENT_PAGE',
  SET_DOCUMENT_SORT:           'SET_DOCUMENT_SORT',
  SET_DOCUMENT_ORDER:          'SET_DOCUMENT_ORDER',
  SET_DOCUMENT_TOTAL_PAGE:     'SET_DOCUMENT_TOTAL_PAGE',
  SET_DOCUMENT_ID:             'SET_DOCUMENT_ID',
  SET_DOCUMENT_ACTION:         'SET_DOCUMENT_ACTION',
  SET_DOCUMENT_USER_ID_ACTION: 'SET_DOCUMENT_USER_ID_ACTION',
  SET_DOCUMENT_RECORD:         'SET_DOCUMENT_RECORD',
  SET_DOCUMENT_ADD:            'SET_DOCUMENT_ADD',
  SET_DOCUMENT_NEEDUPDATE:     'SET_DOCUMENT_NEEDUPDATE',
  RESET_DOCUMENT:              'RESET_DOCUMENT'
}

export default DocumentTypes;