const TransactionTypes = {
  SET_TRANSACTION_DATA:           'SET_TRANSACTION_DATA',
  SET_TRANSACTION_CURRENT_PAGE:   'SET_TRANSACTION_CURRENT_PAGE',
  SET_TRANSACTION_SORT:           'SET_TRANSACTION_SORT',
  SET_TRANSACTION_ORDER:          'SET_TRANSACTION_ORDER',
  SET_TRANSACTION_TOTAL_PAGE:     'SET_TRANSACTION_TOTAL_PAGE',
  SET_TRANSACTION_ID:             'SET_TRANSACTION_ID',
  SET_TRANSACTION_ACTION:         'SET_TRANSACTION_ACTION',
  SET_TRANSACTION_RECORD:         'SET_TRANSACTION_RECORD',
  SET_TRANSACTION_ADD:            'SET_TRANSACTION_ADD',
  RESET_TRANSACTION:              'RESET_TRANSACTION',
}

export default TransactionTypes;