export const headerRoles = {
  admin: [
    {
      path: '/',
      i18: 'clients',
      message: 'Clients',
      class: 'fa fa-users',
      denied: [],
    },
    {
      path: '/services',
      i18: 'services',
      message: 'Services',
      class: 'fa fa-puzzle-piece',
      denied: [],
    },
    {
      path: '/users',
      i18: 'users',
      message: 'Users',
      class: 'fa fa-address-book',
      denied: [],
    },
    {
      path: '/documents',
      i18: 'documents',
      message: 'Documents',
      class: 'fa fa-file-text',
      denied: [],
    },
    {
      path: '/transactions',
      i18: 'transactions',
      message: 'Transactions',
      class: 'fa fa-exchange',
      denied: [],
    },
    {
      path: '/claims',
      i18: 'claims_on_subscribes',
      message: 'Claims on subscribes',
      class: 'fa fa-book',
      denied: [],
    },
  ],
  client: [
    {
      path: '/',
      i18: 'about.company',
      message: 'About company',
      class: 'fa fa-users',
      denied: [],
    },
    {
      path: '/services',
      i18: 'services',
      message: 'Services',
      class: 'fa fa-puzzle-piece',
      denied: [],
    },
    {
      path: '/users',
      i18: 'users',
      message: 'Users',
      class: 'fa fa-address-book',
      denied: [],
    },
    {
      path: '/documents',
      i18: 'documents',
      message: 'Documents',
      class: 'fa fa-file-text',
      denied: [],
    },
    {
      path: '/transactions',
      i18: 'transactions',
      message: 'Transactions',
      class: 'fa fa-exchange',
      denied: [],
    },
  ],
  director: [
    {
      path: '/',
      i18: 'about.company',
      message: 'About company',
      class: 'fa fa-users',
      denied: [],
    },
    {
      path: '/services_client',
      i18: 'services',
      message: 'Services',
      class: 'fa fa-puzzle-piece',
      denied: [],
    },
    {
      path: '/users_client',
      i18: 'users',
      message: 'Users',
      class: 'fa fa-address-book',
      denied: [],
    },
    {
      path: '/documents',
      i18: 'documents',
      message: 'Documents',
      class: 'fa fa-file-text',
      denied: [],
    },
    {
      path: '/transactions_client',
      i18: 'transactions',
      message: 'Transactions',
      class: 'fa fa-exchange',
      denied: [],
    },
  ],
  employee: [
    {
      path: '/',
      i18: 'about.company',
      message: 'About company',
      class: 'fa fa-users',
      denied: [],
    },
    {
      path: '/services_client',
      i18: 'services',
      message: 'Services',
      class: 'fa fa-puzzle-piece',
      denied: [],
    },
    {
      path: '/users_client',
      i18: 'users',
      message: 'Users',
      class: 'fa fa-address-book',
      denied: [],
    },
    {
      path: '/documents',
      i18: 'documents',
      message: 'Documents',
      class: 'fa fa-file-text',
      denied: [],
    },
    {
      path: '/transactions_client',
      i18: 'transactions',
      message: 'Transactions',
      class: 'fa fa-exchange',
      denied: [],
    },
  ],
  manager: [
    {
      path: '/',
      i18: 'clients',
      message: 'Clients',
      class: 'fa fa-users',
      denied: [],
    },
    {
      path: '/services',
      i18: 'services',
      message: 'Services',
      class: 'fa fa-puzzle-piece',
      denied: [],
    },
    {
      path: '/users',
      i18: 'users',
      message: 'Users',
      class: 'fa fa-address-book',
      denied: [],
    },
    {
      path: '/documents',
      i18: 'documents',
      message: 'Documents',
      class: 'fa fa-file-text',
      denied: [],
    },
    {
      path: '/claims',
      i18: 'claims_on_subscribes',
      message: 'Claims on subscribes',
      class: 'fa fa-book',
      denied: [],
    },
    {
      path: '/reports',
      i18: 'reports',
      message: 'Reports',
      class: 'fa fa-table',
      denied: [],
    },
  ],
  observer: [
    {
      path: '/',
      i18: 'clients',
      message: 'Clients',
      class: 'fa fa-users',
      denied: [],
    },
    {
      path: '/services',
      i18: 'services',
      message: 'Services',
      class: 'fa fa-puzzle-piece',
      denied: [],
    },
    {
      path: '/users',
      i18: 'users',
      message: 'Users',
      class: 'fa fa-address-book',
      denied: [],
    },
    {
      path: '/documents',
      i18: 'documents',
      message: 'Documents',
      class: 'fa fa-file-text',
      denied: [],
    },
    {
      path: '/transactions',
      i18: 'transactions',
      message: 'Transactions',
      class: 'fa fa-exchange',
      denied: [],
    },
    {
      path: '/claims',
      i18: 'claims_on_subscribes',
      message: 'Claims on subscribes',
      class: 'fa fa-book',
      denied: [],
    },
    {
      path: '/reports',
      i18: 'reports',
      message: 'Reports',
      class: 'fa fa-table',
      denied: [],
    },
  ],
};
