const SmsloginTypes = {
  SET_SMSLOGIN_DATA:           'SET_SMSLOGIN_DATA',
  SET_SMSLOGIN_CURRENT_PAGE:   'SET_SMSLOGIN_CURRENT_PAGE',
  SET_SMSLOGIN_SORT:           'SET_SMSLOGIN_SORT',
  SET_SMSLOGIN_ORDER:          'SET_SMSLOGIN_ORDER',
  SET_SMSLOGIN_TOTAL_PAGE:     'SET_SMSLOGIN_TOTAL_PAGE',
  SET_SMSLOGIN_ID:             'SET_SMSLOGIN_ID',
  SET_SMSLOGIN_ACTION:         'SET_SMSLOGIN_ACTION',
  SET_SMSLOGIN_RECORD:         'SET_SMSLOGIN_RECORD',
  RESET_SMSLOGIN:              'RESET_SMSLOGIN',
}

export default SmsloginTypes;