const ServiceTypes = {
  SET_SERVICE_DATA:           'SET_SERVICE_DATA',
  SET_SERVICE_CURRENT_PAGE:   'SET_SERVICE_CURRENT_PAGE',
  SET_SERVICE_SORT:           'SET_SERVICE_SORT',
  SET_SERVICE_ORDER:          'SET_SERVICE_ORDER',
  SET_SERVICE_TOTAL_PAGE:     'SET_SERVICE_TOTAL_PAGE',
  SET_SERVICE_ID:             'SET_SERVICE_ID',
  SET_SERVICE_ACTION:         'SET_SERVICE_ACTION',
  SET_SERVICE_USER_ID_ACTION: 'SET_SERVICE_USER_ID_ACTION',
  SET_SERVICE_RECORD:         'SET_SERVICE_RECORD',
  RESET_SERVICE:              'RESET_SERVICE',
  SET_BALANCE:                'SET_BALANCE'
}

export default ServiceTypes;