const ProfileTypes = {
  SET_PROFILE_DATA:           'SET_PROFILE_DATA',
  SET_PROFILE_CURRENT_PAGE:   'SET_PROFILE_CURRENT_PAGE',
  SET_PROFILE_SORT:           'SET_PROFILE_SORT',
  SET_PROFILE_ORDER:          'SET_PROFILE_ORDER',
  SET_PROFILE_TOTAL_PAGE:     'SET_PROFILE_TOTAL_PAGE',
  SET_PROFILE_ID:             'SET_PROFILE_ID',
  SET_PROFILE_ACTION:         'SET_PROFILE_ACTION',
  SET_PROFILE_RECORD:         'SET_PROFILE_RECORD',
  RESET_PROFILE:              'RESET_PROFILE',
}

export default ProfileTypes;