const UserTypes = {
  SET_USER_DATA: 'SET_USER_DATA',
  SET_USER_CURRENT_PAGE: 'SET_USER_CURRENT_PAGE',
  SET_USER_SORT: 'SET_USER_SORT',
  SET_USER_ORDER: 'SET_USER_ORDER',
  SET_USER_TOTAL_PAGE: 'SET_USER_TOTAL_PAGE',
  SET_USER_ID: 'SET_USER_ID',
  SET_USER_ACTION: 'SET_USER_ACTION',
  SET_USER_RECORD: 'SET_USER_RECORD',
  SET_USER_TOKEN: 'SET_USER_TOKEN',
};

export default UserTypes;
