const BalanceTypes = {
  SET_BALANCE_DATA: 'SET_BALANCE_DATA',
  SET_FULL_BALANCE_DATA: 'SET_FULL_BALANCE_DATA',
  SET_BALANCE_NEED_BALANCE: 'SET_BALANCE_NEED_BALANCE',
};

export default BalanceTypes;
